[package]

name = "skarn"
version = "0.0.1"
authors = ["Michael Sproul <micsproul@gmail.com>"]

[[bin]]

name = "skarn"

[dependencies]
glob = "*"
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"

[dependencies.sequence_trie]

git = "https://github.com/michaelsproul/rust-sequence-trie.git"
